#
# C++ sphinx search client library
# Copyright (C) 2007  Seznam.cz, a.s.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# Seznam.cz, a.s.
# Radlicka 2, Praha 5, 15000, Czech Republic
# http://www.seznam.cz, mailto:sphinxclient@firma.seznam.cz
#
#
# $Id: Makefile.test 78 2007-01-08 17:04:36Z jan.kirschner $
#
# DESCRIPTION
# A makefile for sphinxtest.
#
# AUTHORS
# Jan Kirschner <jan.kirschner@firma.seznam.cz>
#
# HISTORY
# 2006-12-14  (kirschner)
#             Created.
#

CXX=g++
CXXFLAGS=-Wall -pedantic -I"./include" -g
#LINKFLAGS=-lsphinxclient -L"./src/.libs"
LINKFLAGS= -g -Od

COMPILE=$(CXX) -c $(CXXFLAGS)
LINK=$(CXX) $(LINKFLAGS)

all: sphinxtest sphinxtest2

sphinxtest: sphinxtest.o src/.libs/libsphinxclient.a
	$(LINK) -o sphinxtest sphinxtest.o src/.libs/libsphinxclient.a

sphinxtest.o: sphinxtest.cc
	$(COMPILE) -o sphinxtest.o sphinxtest.cc

sphinxtest2: sphinxtest2.o src/.libs/libsphinxclient.a
	$(LINK) -o sphinxtest2 sphinxtest2.o src/.libs/libsphinxclient.a

sphinxtest2.o: sphinxtest2.cc
	$(COMPILE) -o sphinxtest2.o sphinxtest2.cc

clean:
	rm -f *.o sphinxtest sphinxtest2
